>6 cargo data vaildation
team4099/FalconScout pull request #7
Opened 2022-11-11 20:02 UTC by eckshn

2022-11-13 02:40 UTC, sswadkar requested changes
lgtm just a few syntax changes

2022-11-13 02:40 UTC, sswadkar commented on backend/data_validation/data_val_2022.py
> +                error_type=ErrorType.INCORRECT_DATA,
i don't think this is INCORRECT_DATA it should be a warning (bc anything higher than 6 is unlikely but still possible).

2022-11-13 02:40 UTC, sswadkar commented on backend/data_validation/data_val_2022.py
> +                f"In {match_key}, {team_number} INCORRECT AUTO SHOT COUNT",
it's not incorrect as much as it is unlikely

2022-11-13 02:40 UTC, sswadkar commented on backend/data_validation/tests/test_data_val_2022.py
> +        scout_id: str = "falcon",
unindent all of these?

2022-11-13 02:41 UTC, sswadkar commented
oh also pls run the lint stuff
this should be done on precommit but if it says `failed` a bunch just `git add .` `git commit -m <old commit message>` and then it should fix everything for you

2022-11-24 16:26 UTC, eckshn commented
> oh also pls run the lint stuff this should be done on precommit but if it says `failed` a bunch just `git add .` `git commit -m <old commit message>` and then it should fix everything for you

lowkey idk what lint is and my python is wacky

2022-12-24 04:07 UTC, merged